from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeneratingFloorResponseSpectraDirectly(object):
    def setupUi(self, GeneratingFloorResponseSpectraDirectly):
        GeneratingFloorResponseSpectraDirectly.setObjectName("GeneratingFloorResponseSpectraDirectly")
        GeneratingFloorResponseSpectraDirectly.resize(948, 464)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(GeneratingFloorResponseSpectraDirectly)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(GeneratingFloorResponseSpectraDirectly)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 229, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(8,46,84)")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setMidLineWidth(-2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(GeneratingFloorResponseSpectraDirectly)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 46, 84, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_10.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(255, 240, 245);\n"
"color:rgb(8,46,84)")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.structuretypes = QtWidgets.QLabel(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.structuretypes.setFont(font)
        self.structuretypes.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.structuretypes.setLineWidth(0)
        self.structuretypes.setObjectName("structuretypes")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.structuretypes)
        self.I = QtWidgets.QComboBox(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.I.setFont(font)
        self.I.setObjectName("I")
        self.I.addItem("")
        self.I.addItem("")
        self.I.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.I)
        self.direction = QtWidgets.QLabel(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.direction.setFont(font)
        self.direction.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.direction.setLineWidth(0)
        self.direction.setObjectName("direction")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.direction)
        self.F = QtWidgets.QComboBox(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.F.setFont(font)
        self.F.setObjectName("F")
        self.F.addItem("")
        self.F.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.F)
        self.dampingratio = QtWidgets.QLabel(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dampingratio.setFont(font)
        self.dampingratio.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dampingratio.setLineWidth(0)
        self.dampingratio.setObjectName("dampingratio")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.dampingratio)
        self.d = QtWidgets.QComboBox(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.d.setFont(font)
        self.d.setObjectName("d")
        self.d.addItem("")
        self.d.addItem("")
        self.d.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.d)
        self.soilconditions = QtWidgets.QLabel(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.soilconditions.setFont(font)
        self.soilconditions.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.soilconditions.setLineWidth(0)
        self.soilconditions.setObjectName("soilconditions")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.soilconditions)
        self.d_2 = QtWidgets.QComboBox(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.d_2.setFont(font)
        self.d_2.setObjectName("d_2")
        self.d_2.addItem("")
        self.d_2.addItem("")
        self.d_2.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.d_2)
        self.Numberofstories = QtWidgets.QLabel(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Numberofstories.setFont(font)
        self.Numberofstories.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Numberofstories.setLineWidth(0)
        self.Numberofstories.setObjectName("Numberofstories")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Numberofstories)
        self.N = QtWidgets.QLineEdit(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.N.setFont(font)
        self.N.setText("")
        self.N.setObjectName("N")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.N)
        self.laterallength = QtWidgets.QLabel(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.laterallength.setFont(font)
        self.laterallength.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.laterallength.setLineWidth(0)
        self.laterallength.setObjectName("laterallength")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.laterallength)
        self.Lt = QtWidgets.QLineEdit(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.Lt.setFont(font)
        self.Lt.setObjectName("Lt")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Lt)
        self.longitudinallength = QtWidgets.QLabel(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.longitudinallength.setFont(font)
        self.longitudinallength.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.longitudinallength.setLineWidth(0)
        self.longitudinallength.setObjectName("longitudinallength")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.longitudinallength)
        self.Ll = QtWidgets.QLineEdit(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.Ll.setFont(font)
        self.Ll.setObjectName("Ll")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.Ll)
        self.totalheight = QtWidgets.QLabel(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.totalheight.setFont(font)
        self.totalheight.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.totalheight.setLineWidth(0)
        self.totalheight.setObjectName("totalheight")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.totalheight)
        self.H = QtWidgets.QLineEdit(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.H.setFont(font)
        self.H.setObjectName("H")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.H)
        self.heightfactor = QtWidgets.QLabel(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.heightfactor.setFont(font)
        self.heightfactor.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.heightfactor.setLineWidth(0)
        self.heightfactor.setObjectName("heightfactor")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.heightfactor)
        self.zh = QtWidgets.QLineEdit(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.zh.setFont(font)
        self.zh.setObjectName("zh")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.zh)
        self.basementstories = QtWidgets.QLabel(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.basementstories.setFont(font)
        self.basementstories.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.basementstories.setLineWidth(0)
        self.basementstories.setObjectName("basementstories")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.basementstories)
        self.B = QtWidgets.QLineEdit(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.B.setFont(font)
        self.B.setObjectName("B")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.B)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.predict = QtWidgets.QPushButton(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.predict.setFont(font)
        self.predict.setStyleSheet("background-color:rgb(100,149,237);\n"
"color:rgb(178,34,34);")
        self.predict.setObjectName("predict")
        self.horizontalLayout_3.addWidget(self.predict)
        self.save = QtWidgets.QPushButton(GeneratingFloorResponseSpectraDirectly)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.save.setFont(font)
        self.save.setStyleSheet("background-color:rgb(100,149,237);\n"
"color:rgb(178,34,34);")
        self.save.setObjectName("save")
        self.horizontalLayout_3.addWidget(self.save)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView_2 = QtWidgets.QGraphicsView(GeneratingFloorResponseSpectraDirectly)
        self.graphicsView_2.setMaximumSize(QtCore.QSize(800, 800))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.horizontalLayout.addWidget(self.graphicsView_2)
        self.graphicsView = QtWidgets.QGraphicsView(GeneratingFloorResponseSpectraDirectly)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(GeneratingFloorResponseSpectraDirectly)
        self.tableWidget.setStyleSheet("QHeaderView::section {background-color:#E8F0F5;}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(31)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(30, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget.verticalHeader().setDefaultSectionSize(60)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(GeneratingFloorResponseSpectraDirectly)
        QtCore.QMetaObject.connectSlotsByName(GeneratingFloorResponseSpectraDirectly)

    def retranslateUi(self, GeneratingFloorResponseSpectraDirectly):
        _translate = QtCore.QCoreApplication.translate
        GeneratingFloorResponseSpectraDirectly.setWindowTitle(_translate("GeneratingFloorResponseSpectraDirectly", "Generating Floor Response Spectra Directly"))
        self.label.setText(_translate("GeneratingFloorResponseSpectraDirectly", "Generating Floor Response Spectra Directly"))
        self.label_10.setText(_translate("GeneratingFloorResponseSpectraDirectly", "Building information"))
        self.structuretypes.setText(_translate("GeneratingFloorResponseSpectraDirectly", "Structure types"))
        self.I.setItemText(0, _translate("GeneratingFloorResponseSpectraDirectly", "concrete"))
        self.I.setItemText(1, _translate("GeneratingFloorResponseSpectraDirectly", "steel"))
        self.I.setItemText(2, _translate("GeneratingFloorResponseSpectraDirectly", "masonry"))
        self.direction.setText(_translate("GeneratingFloorResponseSpectraDirectly", "Direction"))
        self.F.setItemText(0, _translate("GeneratingFloorResponseSpectraDirectly", "lateral"))
        self.F.setItemText(1, _translate("GeneratingFloorResponseSpectraDirectly", "longitudinal"))
        self.dampingratio.setText(_translate("GeneratingFloorResponseSpectraDirectly", "Damping ratio"))
        self.d.setItemText(0, _translate("GeneratingFloorResponseSpectraDirectly", "0.02"))
        self.d.setItemText(1, _translate("GeneratingFloorResponseSpectraDirectly", "0.05"))
        self.d.setItemText(2, _translate("GeneratingFloorResponseSpectraDirectly", "0.1"))
        self.soilconditions.setText(_translate("GeneratingFloorResponseSpectraDirectly", "Soil condition"))
        self.d_2.setItemText(0, _translate("GeneratingFloorResponseSpectraDirectly", "C"))
        self.d_2.setItemText(1, _translate("GeneratingFloorResponseSpectraDirectly", "D"))
        self.d_2.setItemText(2, _translate("GeneratingFloorResponseSpectraDirectly", "E"))
        self.Numberofstories.setText(_translate("GeneratingFloorResponseSpectraDirectly", "Number of stories"))
        self.laterallength.setText(_translate("GeneratingFloorResponseSpectraDirectly", "Transverse length (m)"))
        self.longitudinallength.setText(_translate("GeneratingFloorResponseSpectraDirectly", "Longitudinal length (m)"))
        self.totalheight.setText(_translate("GeneratingFloorResponseSpectraDirectly", "Total height (m)"))
        self.heightfactor.setText(_translate("GeneratingFloorResponseSpectraDirectly", "Relative height of NSCs"))
        self.basementstories.setText(_translate("GeneratingFloorResponseSpectraDirectly", "Number of basement stories"))
        self.predict.setText(_translate("GeneratingFloorResponseSpectraDirectly", "Predict"))
        self.save.setText(_translate("GeneratingFloorResponseSpectraDirectly", "Save"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "FRS/PGA"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "FRS/PFA"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "0"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "0.1"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "0.2"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "0.3"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "0.4"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "0.5"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "0.6"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "0.7"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "0.8"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "0.9"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "1.0"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "1.1"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "1.2"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "1.3"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "1.4"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "1.5"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "1.6"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "1.7"))
        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "1.8"))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "1.9"))
        item = self.tableWidget.horizontalHeaderItem(20)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "2.0"))
        item = self.tableWidget.horizontalHeaderItem(21)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "2.1"))
        item = self.tableWidget.horizontalHeaderItem(22)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "2.2"))
        item = self.tableWidget.horizontalHeaderItem(23)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "2.3"))
        item = self.tableWidget.horizontalHeaderItem(24)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "2.4"))
        item = self.tableWidget.horizontalHeaderItem(25)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "2.5"))
        item = self.tableWidget.horizontalHeaderItem(26)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "2.6"))
        item = self.tableWidget.horizontalHeaderItem(27)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "2.7"))
        item = self.tableWidget.horizontalHeaderItem(28)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "2.8"))
        item = self.tableWidget.horizontalHeaderItem(29)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "2.9"))
        item = self.tableWidget.horizontalHeaderItem(30)
        item.setText(_translate("GeneratingFloorResponseSpectraDirectly", "3.0"))

import pickle
import sys
from PyQt5.QtWidgets import QMessageBox, QApplication, QFileDialog, QWidget
import numpy as np
from functools import partial
import sys
import pickle
import re
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
import matplotlib
 
matplotlib.use("Qt5Agg")
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
from matplotlib.figure import Figure
from matplotlib import pyplot
 
pyplot.rcParams['font.sans-serif'] = ['Times New Roman']
pyplot.rcParams['axes.unicode_minus'] = False



class MyFigure(FigureCanvasQTAgg):
   def __init__(self,width=5,height=4,dpi = 100):
      self.fig = Figure(figsize=(width,height),dpi=dpi)
      super(MyFigure, self).__init__(self.fig)
 
   def plot(self,x,y):
      self.axes0 = self.fig.add_subplot(111)
      self.axes0.plot(x,y)

class MyUiComputer(Ui_GeneratingFloorResponseSpectraDirectly, QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.predict.clicked.connect(partial(self.FRSPredict))
        self.save.clicked.connect(partial(self.Savetxt))

    def FRSPredict(self,window):
        try:
            N1 = self.N.text()
            Lt1 = self.Lt.text()
            Ll1 = self.Ll.text() 
            H1 = self.H.text()
            zh1 = self.zh.text()
            B1 = self.B.text()
            textbox_values = [N1, Lt1, Ll1, H1, zh1, B1]
            I1 = self.I.currentText()
            F1 = self.F.currentText()
            d1 = self.d.currentText()
            S1 = self.d_2.currentText()
            if any([not N1, not Lt1, not Ll1, not H1, not zh1, not B1]):
                QMessageBox.warning(self, 'Warning', 'Please enter a value for all fields.', QMessageBox.Ok)
                return
            textbox_values.append(d1)
            textbox_values = [float(x) for x in textbox_values]
            if F1 == "lateral":
                textbox_values.append(1)
            else:
                textbox_values.append(0)

            if I1 == "concrete":
                textbox_values.extend([1, 0, 0])
            elif I1 == "steel":
                textbox_values.extend([0, 1, 0])
            else:
                textbox_values.extend([0, 0, 1])

            if S1 == "C":
                textbox_values.extend([1, 0, 0])
            elif S1 == "D":
                textbox_values.extend([0, 1, 0])
            else:
                textbox_values.extend([0, 0, 1])
            loaded_model1 = pickle.load(open("PGAXGB.pickle.dat", "rb"))
            loaded_model2 = pickle.load(open("PFAXGB.pickle.dat", "rb"))
        
            inputdata = np.array([])

            Stru = np.tile(textbox_values, (31, 1))
            T = np.arange(0, 3.1, 0.1)
            inputdata = np.concatenate((Stru, np.transpose([T])), axis=1)
            inputdata = np.insert(inputdata, 8, inputdata[:,-1], axis=1)
            inputdata = np.delete(inputdata, -1, axis=1)
            FRS_PGA = loaded_model1.predict(inputdata)
            FRS_PFA = loaded_model2.predict(inputdata)
            self.FRS_PGA = FRS_PGA
            self.FRS_PFA = FRS_PFA
            self.T = T
            self.N1=N1
            self.Ll1=Ll1
            self.Lt1=Lt1
            self.H1=H1
            self.S1=S1
            self.zh1=zh1
            self.B1=B1
            self.I1=I1
            self.F1=F1
            self.d1=d1


        except Exception as e:
            QMessageBox.warning(self, 'Warning', f"Error:{e}.", QMessageBox.Ok)

        F1 = MyFigure(width=5, height=4, dpi=100)
        F1.axes1 = F1.fig.add_subplot(111)
        F1.axes1.plot(T, FRS_PGA)
        # F1.axes1.set_title("FRS/PGA")
        F1.axes1.set_ylim(np.min(FRS_PGA)-0.5, np.ceil(np.max(FRS_PGA)+0.5))
        F1.axes1.set_xticks(np.arange(0, 3.1, 0.5))
        F1.axes1.set_yticks(np.linspace(0, np.ceil(np.max(FRS_PGA)+0.5), 5))
        F1.axes1.set_xlabel("T (s)")
        F1.axes1.set_ylabel("FRS/PGA")
        width,height = self.graphicsView_2.width(),self.graphicsView_2.height()
        F1.resize(width*0.9,height*0.8)
        F1.fig.subplots_adjust(bottom=0.3, left=0.25)

        F2 = MyFigure(width=5, height=4, dpi=100)
        F2.axes1 = F2.fig.add_subplot(111)
        F2.axes1.plot(T, FRS_PFA)
        # F1.axes1.set_title("FRS/PFA")
        F2.axes1.set_ylim(np.min(FRS_PFA)-0.5, np.ceil(np.max(FRS_PFA)+0.5))
        F2.axes1.set_xticks(np.arange(0, 3.1, 0.5))
        F2.axes1.set_yticks(np.linspace(0, np.ceil(np.max(FRS_PFA)+0.5), 5))
        F2.axes1.set_xlabel("T (s)")
        F2.axes1.set_ylabel("FRS/PFA")
        width,height = self.graphicsView.width(),self.graphicsView.height()
        F2.resize(width*0.9,height*0.8)
        F2.fig.subplots_adjust(bottom=0.3, left=0.25)

        self.scene = QGraphicsScene()
        self.scene.addWidget(F1)
        self.graphicsView_2.setScene(self.scene)
        self.scene2 = QGraphicsScene()
        self.scene2.addWidget(F2)
        self.graphicsView.setScene(self.scene2)

        cols_num = self.tableWidget.columnCount()

        FRS_PGA_list = list(FRS_PGA)
        FRS_PFA_list = list(FRS_PFA)

        for i in range(cols_num):           
            FRS_PGA2 = "{:.3f}".format(FRS_PGA_list[i])
            FRS_PFA2 = "{:.3f}".format(FRS_PFA_list[i])
            item_pga = QTableWidgetItem(FRS_PGA2)
            item_pfa = QTableWidgetItem(FRS_PFA2)
            self.tableWidget.setItem(0, i, item_pga)
            self.tableWidget.setItem(1, i, item_pfa)

    def Savetxt(self):
        try:
            data = np.concatenate((np.transpose([self.T]), np.transpose([self.FRS_PGA]), np.transpose([self.FRS_PFA])), axis=1)

            options = QFileDialog.Options()
            filePath, _ = QFileDialog.getSaveFileName(self, "Save File", "", "Text Files (*.txt)", options=options)

            if filePath:
                line1 = 'Number of stories: {}'.format(self.N1)
                line2 = 'Lateral length (m): {}'.format(self.Lt1)
                line3 = 'Longitudinal length (m): {}'.format(self.Ll1)
                line4 = 'Total height (m): {}'.format(self.H1)
                line6 = 'Relative height of NSCs: {}'.format(self.zh1)
                line7 = 'Number of basement stories: {}'.format(self.B1)
                line8 = 'Structure types: {}'.format(self.I1)
                line9 = 'Direction: {}'.format(self.F1)
                line10 = 'Damping ratio: {}'.format(self.d1)
                line5 = 'Soil condition: {}'.format(self.S1)
                column_names = ['T', 'FRS/PGA', 'FRS/PFA']
                header_lines = [line1, line2, line3, line4, line6, line7, line8, line9, line10, line5]
                header = '\n'.join(header_lines) + '\n' + '\t'.join(column_names)
                np.savetxt(filePath, data, fmt='%0.3f', header=header, comments='')
        except Exception as e:
            QMessageBox.warning(self, 'Warning', f"Error:{e}.", QMessageBox.Ok)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    demo = MyUiComputer()
    demo.show()
    sys.exit(app.exec_())